(function(a){a.jInvertScroll=function(b,d){function c(){a.each(b,function(b,c){a(c).each(function(b){m.push(a(this));b=a(this).width();h<b&&(h=b)})});"auto"==f.width&&(f.width=h);"auto"==f.height&&(f.height=h);a("body").css("height",f.height+"px")}function e(){n=a(document).height();g=a(window).height();p=a(window).width()}function k(b){b=a(this).scrollTop();e();var c=n-g,d=0;0!=c&&(d=(b/c).toFixed(4));"function"===typeof f.onScroll&&f.onScroll.call(this,d);a.each(m,function(a,b){var c=b.width()-
p;0>=c&&(c=b.width());b.css("left",-1*Math.floor(c*d))})}function l(){a(window).on("scroll resize",k);a([document,window]).on("ready resize",e)}var f=a.extend({width:"auto",height:"auto",onScroll:function(a){}},d);if(!("Object"===typeof b&&0<b.length)){var m=[],h=0,n,g,p;c();l();return{reinitialize:function(){c();l()},destroy:function(){a("body").attr("style","");a(window).off("scroll resize",k);a([document,window]).off("ready resize",e)}}}}})(jQuery);
var $ken=$("#dipt"),casualclothes=document.getElementById("casualsvg"),gradclothes=document.getElementById("gradsvg"),formalclothes=document.getElementById("formalsvg"),cstart=document.getElementById("cstart"),gstart=document.getElementById("gstart"),fstart=document.getElementById("fstart");cstart.beginElement();gstart.beginElement();fstart.beginElement();
var currentclothes=cstart,$initialize=$("#initialize"),$chkpoint1=$("#chkpoint1"),$chkpoint2=$("#chkpoint2"),$chkpoint3=$("#chkpoint3"),$chkpoint4=$("#chkpoint4"),$chkpoint5=$("#chkpoint5"),$finale=$("#finale"),$flagpole=$(".flagpole"),$key=$(".key4"),$kenPos,$fireballPos,$introbck=$(".name"),$intromsg=$(".intromsg"),$college=$("#college"),$collegeribbon=$("#collegeribbon"),$gradBtn=$("#gradBtn"),$office=$(".office"),$officeribbon=$("#officeribbon"),$officeBtn=$("#officeBtn"),$billboard=$("#billboard"),
$blimp=$("#blimp"),$htmlribbon=$("#htmlribbon"),$cssribbon=$("#cssribbon"),$jsribbon=$("#jsribbon"),$jqueryribbon=$("#jqueryribbon"),$photoshopribbon=$("#photoshopribbon"),$illustratorribbon=$("#illustratorribbon"),$bootribbon=$("#bootribbon"),$csharpribbon=$("#csharpribbon"),$noderibbon=$("#noderibbon"),$sassribbon=$("#sassribbon"),$reactribbon=$("#reactribbon"),$fluxribbon=$("#fluxribbon"),$polymerribbon=$("#polymerribbon"),$learn=$(".learn"),$skill=$(".skill"),$contactBtn=$("#contactBtn"),$cannon=
$(".cannon"),$wall=$(".wall"),$contactheading=$(".contactheading"),$nameinput=$("#nameinput"),$emailinput=$("#emailinput"),$msginput=$(".msg"),$txtmsg=$(".large"),$submit=$(".submit"),$socialinput=$(".socialinput"),$txtname=$("#txtname"),$txtemail=$("#txtemail"),$sendBtn=$(".sendBtn"),$socialset=$(".socialset"),$navpoint=$(".navpoint"),messagehidden=!1,reachedCollege=!1,reachedOffice=!1,reachedbillboard=!1,reachedSkills=!1,reachedLearn=!1,reachedContact=!1,firedCannon=!1,IsForwardMoving=!0,htmlribbon=
"images/htmlribbon.png",cssribbon="images/cssribbon.png",jsribbon="images/jsribbon.png",jqueryribbon="images/jqribbon.png",photoshopribbon="images/psribbon.png",illustratorribbon="images/illustratorribbon.png",bootribbon="images/bootribbon.png",csharpribbon="images/csharpribbon.png",noderibbon="images/noderibbon.png",sassribbon="images/sassribbon.png",reactribbon="images/reactribbon.png",fluxribbon="images/fluxribbon.png",polymerribbon="images/polymerribbon.png";progress=prev=0;
window.onload=function(){hideall();setupStart();genClips()};
var hideall=function(){gradclothes.style.display="none";formalclothes.style.display="none";$introbck.hide();$intromsg.hide();$college.hide();$collegeribbon.hide();$gradBtn.hide();$office.hide();$officeribbon.hide();$officeBtn.hide();$htmlribbon.hide();$cssribbon.hide();$jsribbon.hide();$jqueryribbon.hide();$photoshopribbon.hide();$illustratorribbon.hide();$bootribbon.hide();$csharpribbon.hide();$noderibbon.hide();$sassribbon.hide();$reactribbon.hide();$fluxribbon.hide();$polymerribbon.hide();$contactBtn.hide();
$contactheading.hide();$nameinput.hide();$emailinput.hide();$txtname.hide();$txtemail.hide();$txtmsg.hide();$msginput.hide();$submit.hide();$socialinput.hide();$sendBtn.hide();$socialset.hide()};$(window).on("beforeunload",function(){$(window).scrollTop(0)});$(document).keydown(function(a){39==a.which&&window.scrollBy(0,50);37==a.which&&window.scrollBy(0,-50)});
(function(a){var b=a.jInvertScroll([".scroll"],{height:15E3,onScroll:function(a){progress=a}});a(window).resize(function(){768>=a(window).width()?b.destroy():b.reinitialize()})})(jQuery);window.onscroll=scroll;function scroll(){currentclothes.beginElement();$ken.css({marginLeft:5400*progress+"px"});update(progress,function(a){a&&console.log("error")});UpdateNav(progress)}
var update=function(a,b){prev>a?(IsForwardMoving=!1,$ken.addClass("reverse")):(IsForwardMoving=!0,$ken.removeClass("reverse"));.03>=a&&.03<prev&&displaymsg();.03<a&&updateforwards(a,function(d){d?(console.log("position :"+a),prev=a,console.log(d),b(d)):(prev=a,b(null))})},setupStart=function(){resettxtvalues();$initialize.addClass("current");setTimeout(dropInIntroTxt,1800);setTimeout(showCharacter,2300);setTimeout(displaymsg,3500)},resettxtvalues=function(){$txtname.val("");$txtemail.val("");$txtmsg.val("")},
dropInIntroTxt=function(){$introbck.show().animate({bottom:"60px"},700)},showCharacter=function(){0==progress&&$ken.animate({marginLeft:"0px"},1800)},displaymsg=function(){$intromsg.show();messagehidden=!1},hidemsg=function(){$intromsg.hide();messagehidden=!0},updateforwards=function(a,b){.3>a&&(0==messagehidden&&hidemsg(),0==reachedCollege&&.12<a&&(checkPoint1Animate(),reachedCollege=!0),1==reachedCollege&&.2<a&&showgradBtn());.31<a&&.45>a&&(0==reachedOffice&&(checkPoint2Animate(),reachedOffice=
!0),1==reachedOffice&&.36<a&&showofficeBtn());.46<a&&.57>a&&0==reachedbillboard&&(checkPoint3Animate(),reachedbillboard=!0);.7<a&&.8>a&&0==reachedSkills&&(checkPoint6Animate(),reachedSkills=!0);.85<a&&.92>a&&0==reachedLearn&&(checkPoint8Animate(),reachedLearn=!0);.94<a&&0==reachedContact&&(showContactBtn(),reachedContact=!0);console.log(a);b(null)},checkPoint1Animate=function(){popupCollege();setTimeout(dropCollegeRibbon,300)},checkPoint2Animate=function(){popupOffice();setTimeout(dropOfficeRibbon,
500)},checkPoint3Animate=function(){liftbillBoard();moveBlimp()},checkPoint6Animate=function(){setBackgroundImg();SkillRibbonsAnimation()},checkPoint8Animate=function(){setBackgroundImgLearn();LearnRibbonsAnimation()},popupCollege=function(){$college.css({marginBottom:"-400px"});$college.show().animate({marginBottom:"16px"},300)},popupOffice=function(){$office.css({marginBottom:"-400px"});$office.show().animate({marginBottom:"0px"},200)},dropCollegeRibbon=function(){$collegeribbon.css({marginBottom:"400px"});
$collegeribbon.show().animate({marginBottom:"0px"},300)},dropOfficeRibbon=function(){$officeribbon.css({marginBottom:"400px"});$officeribbon.show().animate({marginBottom:"0px"},300)},showgradBtn=function(){$gradBtn.fadeIn(500)},showofficeBtn=function(){$officeBtn.fadeIn(500)},liftbillBoard=function(){$billboard.animate({height:"341px"},300)},moveBlimp=function(){$blimp.animate({marginLeft:"0px"},5E3)},setBackgroundImg=function(){$htmlribbon.css("backgroundImage","url("+htmlribbon+")");$cssribbon.css("backgroundImage",
"url("+cssribbon+")");$jsribbon.css("backgroundImage","url("+jsribbon+")");$jqueryribbon.css("backgroundImage","url("+jqueryribbon+")");$photoshopribbon.css("backgroundImage","url("+photoshopribbon+")");$illustratorribbon.css("backgroundImage","url("+illustratorribbon+")");$bootribbon.css("backgroundImage","url("+bootribbon+")");$csharpribbon.css("backgroundImage","url("+csharpribbon+")");$noderibbon.css("backgroundImage","url("+noderibbon+")")},setBackgroundImgLearn=function(){$sassribbon.css("backgroundImage",
"url("+sassribbon+")");$reactribbon.css("backgroundImage","url("+reactribbon+")");$fluxribbon.css("backgroundImage","url("+fluxribbon+")");$polymerribbon.css("backgroundImage","url("+polymerribbon+")")},SkillRibbonsAnimation=function(){var a=0;$skill.each(function(b,d){setRibbonMargin($(this),a);Animateribbon($(this));a+=78})},LearnRibbonsAnimation=function(){var a=0;$learn.each(function(b,d){setRibbonMargin($(this),a);AnimateLearn($(this));a+=82})},setRibbonMargin=function(a,b){a.css("marginLeft",
b+"px")},Animateribbon=function(a){a.hasClass("master")?AnimateMaster(a):a.hasClass("expert")?AnimateExpert(a):a.hasClass("proficient")?AnimateProficient(a):a.hasClass("familiar")?AnimateFamiliar(a):a.hasClass("beginner")&&AnimateBeginner(a)},AnimateMaster=function(a){a.show().animate({height:"500px",bottom:"1px"},1500)},AnimateExpert=function(a){a.show().animate({height:"433px",bottom:"0px"},1500)},AnimateProficient=function(a){a.show().animate({height:"364px",bottom:"-1px"},1500)},AnimateFamiliar=
function(a){a.show().animate({height:"293px",bottom:"-1px"},1500)},AnimateBeginner=function(a){a.show().animate({height:"221px",bottom:"-1px"},1500)},AnimateLearn=function(a){a.show().animate({height:"293px",bottom:"10px"},1500)},showContactBtn=function(){$contactBtn.fadeIn(500)},hadoken=function(){presscontactBtn();setTimeout(function(){var a=$("<div/>",{"class":"fireball"});a.appendTo($cannon);if(0==firedCannon)var b=setInterval(function(){$fireballPos=a.offset();45>=$wall.offset().left-$fireballPos.left&&
-45<=$wall.offset().left-$fireballPos.left&&(firedCannon=!0,a.addClass("explode").removeClass("moving").css("marginLeft","+=22px"),clearInterval(b),setTimeout(function(){a.remove()},500),AnimateFinale())},50);setTimeout(function(){a.addClass("moving")},20);setTimeout(function(){a.remove();clearInterval(b)},2E3)},250)},AnimateFinale=function(){explodewall();setTimeout(popContactRibbons,1200)},popContactRibbons=function(){hoistheadingribbon();setTimeout(opennameribbon,800);setTimeout(openemailribbon,
1200);setTimeout(openmsgribbon,1600);setTimeout(opensendribbon,2E3);setTimeout(opensocialribbon,2200)},hoistheadingribbon=function(a){$contactheading.show().animate({bottom:"0px"},500);setTimeout(showribbons,500);setTimeout(openheadingribbon,500)},openheadingribbon=function(){$contactheading.removeClass("closed");$contactheading.addClass("open")},showribbons=function(){$nameinput.show();$emailinput.show();$msginput.removeClass("msg");$msginput.show();$submit.show();$socialinput.show()},opennameribbon=
function(){$nameinput.removeClass("txtinputclose");$nameinput.addClass("txtinputopen");setTimeout(function(){$txtname.show()},400)},openemailribbon=function(){$emailinput.removeClass("txtemailclose");$emailinput.addClass("txtinputopen");setTimeout(function(){$txtemail.show()},400)},openmsgribbon=function(){$msginput.removeClass("txtmsgclose");$msginput.addClass("msg");$msginput.addClass("txtinputopen");setTimeout(function(){$txtmsg.show()},400)},opensendribbon=function(){$submit.removeClass("buttonclose");
setTimeout(function(){$sendBtn.show()},400)},opensocialribbon=function(){$socialinput.animate({width:"240px"},300);setTimeout(function(){$socialset.show()},1E3)},graduate=function(){pressgradBtn();currentclothes==gstart?casuals():(currentclothes=gstart,casualclothes.style.display="none",gradclothes.style.display="block",formalclothes.style.display="none")},formals=function(){pressofficeBtn();currentclothes==fstart?casuals():(currentclothes=fstart,casualclothes.style.display="none",gradclothes.style.display=
"none",formalclothes.style.display="block")},casuals=function(){currentclothes=cstart;casualclothes.style.display="block";formalclothes.style.display="none";gradclothes.style.display="none"},UpdateNav=function(a){.17>a&&resetCurrent(function(){$initialize.addClass("current")});.17<a&&.35>a&&resetCurrent(function(){$chkpoint1.addClass("current")});.35<a&&.46>a&&resetCurrent(function(){$chkpoint2.addClass("current")});.46<a&&.7>a&&resetCurrent(function(){$chkpoint3.addClass("current")});.7<a&&.85>a&&
resetCurrent(function(){$chkpoint4.addClass("current")});.85<a&&.98>a&&resetCurrent(function(){$chkpoint5.addClass("current")});.98<a&&resetCurrent(function(){$finale.addClass("current")})},resetCurrent=function(a){$navpoint.each(function(a,d){$(this).removeClass("current")});a()},scrolltostart=function(){$("html,body").animate({scrollTop:0},{duration:1500,easing:"swing"})},scrolltocollege=function(){$("html,body").animate({scrollTop:3E3},{duration:1500,easing:"swing"})},scrolltooffice=function(){$("html,body").animate({scrollTop:5800},
{duration:1500,easing:"swing"})},scrolltobillboard=function(){$("html,body").animate({scrollTop:8E3},{duration:1500,easing:"swing"})},scrolltoskills=function(){$("html,body").animate({scrollTop:11E3},{duration:1500,easing:"swing"})},scrolltolearn=function(){$("html,body").animate({scrollTop:13E3},{duration:1500,easing:"swing"})},scrolltofinale=function(){$("html,body").animate({scrollTop:14300},{duration:1500,easing:"swing"})};$contactBtn.click(hadoken);$gradBtn.click(graduate);$officeBtn.click(formals);
$initialize.click(scrolltostart);$chkpoint1.click(scrolltocollege);$chkpoint2.click(scrolltooffice);$chkpoint3.click(scrolltobillboard);$chkpoint4.click(scrolltoskills);$chkpoint5.click(scrolltolearn);$finale.click(scrolltofinale);
var presscontactBtn=function(){$contactBtn.addClass("key3press");setTimeout(function(){$contactBtn.removeClass("key3press")},100)},pressgradBtn=function(){$gradBtn.addClass("key1press");setTimeout(function(){$gradBtn.removeClass("key1press")},100)},pressofficeBtn=function(){$officeBtn.addClass("key2press");setTimeout(function(){$officeBtn.removeClass("key2press")},100)},hidewall=function(){$(".clipped-box").hide()},genClips=function(){$t=$(".clipped-box");var a=$t.width()/5,b=$t.height()/5;Math.pow(5,
2);for(var d=$t.find(".content").html(),c=0,e=0;e<=5*a;e+=a)$('<div class="clipped" style="clip: rect('+c+"px, "+(e+a)+"px, "+(c+b)+"px, "+e+'px)">'+d+"</div>").appendTo($t),e===5*a-a&&(c+=b,e=-a),c===5*b&&(e=9999999)};function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
var first=!1,clicked=!1,explodewall=function(){!1===clicked&&(clicked=!0,setTimeout(hidewall,4E3),$(".clipped-box .content").css({display:"none"}),$(".clipped-box div:not(.content)").each(function(){var a=rand(120,90),b=rand(80,89)*Math.PI/180,d=$(this),c=0,e,k,l,f=[1,-1,0],m=f[Math.floor(Math.random()*f.length)],f=rand(-5,10),h=rand(.9,1.1),n=rand(30,5),g=$(this).css("backgroundColor").split("rgb(")[1].split(")")[0].split(", "),p=rand(-20,20),q=rand(-20,20),g="rgb("+(parseFloat(g[0])+p)+", "+(parseFloat(g[1])+
q)+", "+(parseFloat(g[2])+q)+")";$(this).css({transform:"scale("+h+") skew("+f+"deg) rotateZ("+n+"deg)",background:g});e=setInterval(function(){var f=Math.cos(b)*a*m,g=Math.sin(b)*a-9.8*c;k=f*c;l=g*c+-4.9*Math.pow(c,2);$(d).css({bottom:l+"px",left:k+"px"});c+=.1;15<c&&(clicked=!1,first=!0,$(".clipped-box").css({top:"-1000px",transition:"none"}),$(d).css({left:"0",bottom:"0",opacity:"1",transition:"none",transform:"none"}),clearInterval(e))},10)}))};