(function(a){a.jInvertScroll=function(b,c){function g(){a.each(b,function(b,c){a(c).each(function(b){h.push(a(this));b=a(this).width();d<b&&(d=b)})});"auto"==e.width&&(e.width=d);"auto"==e.height&&(e.height=d);a("body").css("height",e.height+"px")}function f(){k=a(document).height();l=a(window).height();m=a(window).width()}function n(b){b=a(this).scrollTop();f();var c=k-l,d=0;0!=c&&(d=(b/c).toFixed(4));"function"===typeof e.onScroll&&e.onScroll.call(this,d);a.each(h,function(a,b){var c=b.width()-
m;0>=c&&(c=b.width());b.css("left",-1*Math.floor(c*d))})}function p(){a(window).on("scroll resize",n);a([document,window]).on("ready resize",f)}var e=a.extend({width:"auto",height:"auto",onScroll:function(a){}},c);if(!("Object"===typeof b&&0<b.length)){var h=[],d=0,k,l,m;g();p();return{reinitialize:function(){g();p()},destroy:function(){a("body").attr("style","");a(window).off("scroll resize",n);a([document,window]).off("ready resize",f)}}}}})(jQuery);
var $ken=$("#dipt"),$guile=$(".guile"),$key=$(".key4"),$kenPos,$guilePos,$fireballPos,$introbck=$(".name"),$intromsg=$(".intromsg"),$college=$("#college"),$collegeribbon=$("#collegeribbon"),$gradBtn=$("#gradBtn"),$office=$(".office"),$officeribbon=$("#officeribbon"),$officeBtn=$("#officeBtn"),$billboard=$("#billboard"),$contactfrm=$("#contactfrm"),$htmlribbon=$("#htmlribbon"),$cssribbon=$("#cssribbon"),$jsribbon=$("#jsribbon"),$jqueryribbon=$("#jqueryribbon"),$photoshopribbon=$("#photoshopribbon"),
$illustratorribbon=$("#illustratorribbon"),$bootribbon=$("#bootribbon"),$csharpribbon=$("#csharpribbon"),$noderibbon=$("#noderibbon"),$sassribbon=$("#sassribbon"),$reactribbon=$("#reactribbon"),$fluxribbon=$("#fluxribbon"),$polymerribbon=$("#polymerribbon"),$learn=$(".learn"),$skill=$(".skill"),$contactBtn=$("#contactBtn"),$cannon=$(".cannon"),$contactribbon=$(".contactribbon"),messagehidden=!1,reachedCollege=!1,reachedOffice=!1,reachedbillboard=!1,reachedSkills=!1,reachedLearn=!1,htmlribbon="images/htmlribbon.png",
cssribbon="images/cssribbon.png",jsribbon="images/jsribbon.png",jqueryribbon="images/jqribbon.png",photoshopribbon="images/psribbon.png",illustratorribbon="images/illustratorribbon.png",bootribbon="images/bootribbon.png",csharpribbon="images/csharpribbon.png",noderibbon="images/noderibbon.png",sassribbon="images/sassribbon.png",reactribbon="images/reactribbon.png",fluxribbon="images/fluxribbon.png",polymerribbon="images/polymerribbon.png";progress=prev=0;
var IsForwardMoving=!0,ani_data=[0,-120,-240,-360],frame_index=0,scrollTimer=null;window.onload=function(){hideall();setupStart()};
var hideall=function(){$introbck.hide();$intromsg.hide();$college.hide();$collegeribbon.hide();$gradBtn.hide();$office.hide();$officeribbon.hide();$officeBtn.hide();$contactfrm.hide();$htmlribbon.hide();$cssribbon.hide();$jsribbon.hide();$jqueryribbon.hide();$photoshopribbon.hide();$illustratorribbon.hide();$bootribbon.hide();$csharpribbon.hide();$noderibbon.hide();$sassribbon.hide();$reactribbon.hide();$fluxribbon.hide();$polymerribbon.hide();$contactribbon.hide()};$(window).on("beforeunload",function(){$(window).scrollTop(0)});
(function(a){var b=a.jInvertScroll([".scroll"],{height:15E3,onScroll:function(a){progress=a}});a(window).resize(function(){768>=a(window).width()?b.destroy():b.reinitialize()})})(jQuery);window.onscroll=scroll;function scroll(){scrollTimer&&clearTimeout(scrollTimer);scrollTimer=setTimeout(animateWalk,18);$ken.css({marginLeft:5400*progress+"px"});update(progress,function(a){a&&console.log("error")})}
function animateWalk(){scrollTimer=null;IsForwardMoving?$ken.css("background-position",ani_data[frame_index]+"px 0px"):$ken.css("background-position",ani_data[frame_index]+"px -160px");frame_index++;frame_index>=ani_data.length&&(frame_index=0)}
var update=function(a,b){IsForwardMoving=prev>a?!1:!0;.03>=a&&.03<prev&&displaymsg();.99>a&&.03<a&&updateforwards(a,function(c){c?(console.log("position :"+a),prev=a,console.log(c),b(c)):(prev=a,b(null))})},setupStart=function(){setTimeout(dropInIntroTxt,1800);setTimeout(showCharacter,2300);setTimeout(displaymsg,3500)},dropInIntroTxt=function(){$introbck.show().animate({bottom:"60px"},700)},showCharacter=function(){0==progress&&$ken.animate({marginLeft:"0px"},1800)},displaymsg=function(){$intromsg.show();
messagehidden=!1},hidemsg=function(){$intromsg.hide();messagehidden=!0},updateforwards=function(a,b){.3>a&&(0==messagehidden&&hidemsg(),0==reachedCollege&&.12<a&&(checkPoint1Animate(),reachedCollege=!0),1==reachedCollege&&.2<a&&showgradBtn());.31<a&&.45>a&&(0==reachedOffice&&(checkPoint2Animate(),reachedOffice=!0),1==reachedOffice&&.36<a&&showofficeBtn());.46<a&&.57>a&&0==reachedbillboard&&(checkPoint3Animate(),reachedbillboard=!0);.7<a&&.8>a&&0==reachedSkills&&(checkPoint6Animate(),reachedSkills=
!0);.85<a&&.92>a&&0==reachedLearn&&(checkPoint8Animate(),reachedLearn=!0);console.log(a);b(null)},updatebackwards=function(a,b){b(null)},setupFinale=function(a){a(null)},checkPoint1Animate=function(){popupCollege();setTimeout(dropCollegeRibbon,500)},checkPoint2Animate=function(){popupOffice();setTimeout(dropOfficeRibbon,500)},checkPoint3Animate=function(){liftbillBoard()},checkPoint6Animate=function(){setBackgroundImg();SkillRibbonsAnimation()},checkPoint8Animate=function(){setBackgroundImgLearn();
LearnRibbonsAnimation()},popupCollege=function(){$college.css({marginBottom:"-400px"});$college.show().animate({marginBottom:"16px"},400)},popupOffice=function(){$office.css({marginBottom:"-400px"});$office.show().animate({marginBottom:"0px"},400)},dropCollegeRibbon=function(){$collegeribbon.css({marginBottom:"400px"});$collegeribbon.show().animate({marginBottom:"0px"},500)},dropOfficeRibbon=function(){$officeribbon.css({marginBottom:"400px"});$officeribbon.show().animate({marginBottom:"0px"},500)},
showgradBtn=function(){$gradBtn.show()},showofficeBtn=function(){$officeBtn.show()},liftbillBoard=function(){$billboard.animate({height:"341px"},400)},setBackgroundImg=function(){$htmlribbon.css("backgroundImage","url("+htmlribbon+")");$cssribbon.css("backgroundImage","url("+cssribbon+")");$jsribbon.css("backgroundImage","url("+jsribbon+")");$jqueryribbon.css("backgroundImage","url("+jqueryribbon+")");$photoshopribbon.css("backgroundImage","url("+photoshopribbon+")");$illustratorribbon.css("backgroundImage",
"url("+illustratorribbon+")");$bootribbon.css("backgroundImage","url("+bootribbon+")");$csharpribbon.css("backgroundImage","url("+csharpribbon+")");$noderibbon.css("backgroundImage","url("+noderibbon+")")},setBackgroundImgLearn=function(){$sassribbon.css("backgroundImage","url("+sassribbon+")");$reactribbon.css("backgroundImage","url("+reactribbon+")");$fluxribbon.css("backgroundImage","url("+fluxribbon+")");$polymerribbon.css("backgroundImage","url("+polymerribbon+")")},SkillRibbonsAnimation=function(){var a=
0;$skill.each(function(b,c){setRibbonMargin($(this),a);Animateribbon($(this));a+=78})},LearnRibbonsAnimation=function(){var a=0;$learn.each(function(b,c){setRibbonMargin($(this),a);AnimateLearn($(this));a+=82})},setRibbonMargin=function(a,b){a.css("marginLeft",b+"px")},Animateribbon=function(a){a.hasClass("master")?AnimateMaster(a):a.hasClass("expert")?AnimateExpert(a):a.hasClass("proficient")?AnimateProficient(a):a.hasClass("familiar")?AnimateFamiliar(a):a.hasClass("beginner")&&AnimateBeginner(a)},
AnimateMaster=function(a){a.show().animate({height:"500px",bottom:"1px"},1500)},AnimateExpert=function(a){a.show().animate({height:"433px",bottom:"0px"},1500)},AnimateProficient=function(a){a.show().animate({height:"364px",bottom:"-1px"},1500)},AnimateFamiliar=function(a){a.show().animate({height:"293px",bottom:"-1px"},1500)},AnimateBeginner=function(a){a.show().animate({height:"221px",bottom:"-1px"},1500)},AnimateLearn=function(a){a.show().animate({height:"293px",bottom:"10px"},1500)},hadoken=function(){setTimeout(function(){var a=
$("<div/>",{"class":"fireball"});a.appendTo($cannon);var b=setInterval(function(){$fireballPos=a.offset();75>=$guile.offset().left-$fireballPos.left&&-75<=$guile.offset().left-$fireballPos.left&&(a.addClass("explode").removeClass("moving").css("marginLeft","+=22px"),clearInterval(b),setTimeout(function(){a.remove()},500),AnimateFinale())},50);setTimeout(function(){a.addClass("moving")},20);setTimeout(function(){a.remove();clearInterval(b)},3020)},250)},AnimateFinale=function(){$guile.addClass("falldown");
$contactBtn.css("display","none");setTimeout(dropContactribbon,200);setTimeout(popContactFrm,500)},popContactFrm=function(){$("#contactfrm").show(function(){$("#contactfrm").addClass("contactopen")})},dropContactribbon=function(){$contactribbon.css({marginBottom:"400px"});$contactribbon.show().animate({marginBottom:"0px"},600)},graduate=function(){$ken.hasClass("grad")?casuals():($ken.removeClass(),$ken.addClass("grad"))},formals=function(){$ken.hasClass("formal")?casuals():($ken.removeClass(),$ken.addClass("formal"))},
casuals=function(){$ken.removeClass();$ken.addClass("casual")};$contactBtn.click(hadoken);$gradBtn.click(graduate);$officeBtn.click(formals);